# Generated by Django 3.2.5 on 2021-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210715_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adm_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
